ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 2
warningCode = 1
[rule.blank-imports]
[rule.confusing-naming]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.exported]
[rule.if-return]
[rule.var-naming]
[rule.var-declaration]
[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.time-naming]
[rule.unexported-return]
[rule.indent-error-flow]
[rule.errorf]
[rule.empty-block]
[rule.superfluous-else]
[rule.unused-parameter]
[rule.unreachable-code]
[rule.redefines-builtin-id]
[rule.line-length-limit]
  arguments = [100]
[rule.cyclomatic]
  arguments = [10]
[imports-blacklist]
  arguments =["log", "math/rand"]
[rule.unnecessary-stmt]
[rule.struct-tag]
[rule.unused-receiver]
